/**
 * Referencia de alimentos con valores aproximados por porción típica.
 * Basado en tablas nutricionales estándar (por 100 g o porción común).
 * Sirve para rellenar calorías, proteínas y carbohidratos al registrar comidas.
 */

import { sinAcentos } from './calorias.js'

export const REFERENCIA_ALIMENTOS = [
  // Desayunos y lácteos
  { categoria: 'Desayuno / Lácteos', nombre: 'Avena con leche (1 taza)', calorias: 150, proteinas: 5, carbohidratos: 27, porcion: '1 taza' },
  { categoria: 'Desayuno / Lácteos', nombre: 'Pan integral (1 rebanada)', calorias: 80, proteinas: 4, carbohidratos: 14, porcion: '1 rebanada' },
  { categoria: 'Desayuno / Lácteos', nombre: 'Pan blanco (1 rebanada)', calorias: 70, proteinas: 2, carbohidratos: 13, porcion: '1 rebanada' },
  { categoria: 'Desayuno / Lácteos', nombre: 'Leche entera (1 vaso)', calorias: 150, proteinas: 8, carbohidratos: 12, porcion: '1 vaso 250 ml' },
  { categoria: 'Desayuno / Lácteos', nombre: 'Leche desnatada (1 vaso)', calorias: 85, proteinas: 8, carbohidratos: 12, porcion: '1 vaso 250 ml' },
  { categoria: 'Desayuno / Lácteos', nombre: 'Yogur natural (1 unidad)', calorias: 100, proteinas: 5, carbohidratos: 12, porcion: '1 unidad 125 g' },
  { categoria: 'Desayuno / Lácteos', nombre: 'Yogur griego (1 unidad)', calorias: 130, proteinas: 10, carbohidratos: 6, porcion: '1 unidad 170 g' },
  { categoria: 'Desayuno / Lácteos', nombre: 'Huevo revuelto (2 huevos)', calorias: 180, proteinas: 12, carbohidratos: 2, porcion: '2 huevos' },
  { categoria: 'Desayuno / Lácteos', nombre: 'Huevo cocido (1 unidad)', calorias: 78, proteinas: 6, carbohidratos: 0.5, porcion: '1 huevo' },
  { categoria: 'Desayuno / Lácteos', nombre: 'Café con leche', calorias: 50, proteinas: 3, carbohidratos: 5, porcion: '1 taza' },
  { categoria: 'Desayuno / Lácteos', nombre: 'Tostadas con mermelada (2 unid)', calorias: 180, proteinas: 4, carbohidratos: 36, porcion: '2 tostadas' },
  {
    categoria: 'Desayuno / Lácteos',
    nombre: 'Tostadas con huevo y palta (aguacate)',
    calorias: 430,
    proteinas: 18,
    carbohidratos: 34,
    porcion: '2 tostadas integrales, 2 huevos, 1/2 palta',
  },
  { categoria: 'Desayuno / Lácteos', nombre: 'Croissant (1 unidad)', calorias: 230, proteinas: 5, carbohidratos: 26, porcion: '1 unidad' },
  { categoria: 'Desayuno / Lácteos', nombre: 'Fruta (plátano mediano)', calorias: 105, proteinas: 1, carbohidratos: 27, porcion: '1 plátano' },
  { categoria: 'Desayuno / Lácteos', nombre: 'Manzana (1 unidad)', calorias: 95, proteinas: 0.5, carbohidratos: 25, porcion: '1 manzana' },
  { categoria: 'Desayuno / Lácteos', nombre: 'Zumo de naranja (1 vaso)', calorias: 110, proteinas: 2, carbohidratos: 26, porcion: '1 vaso 250 ml' },
  { categoria: 'Desayuno / Lácteos', nombre: 'Panqueque de avena (1 unidad)', calorias: 120, proteinas: 5, carbohidratos: 18, porcion: '1 panqueque' },
  { categoria: 'Desayuno / Lácteos', nombre: 'Panqueques de avena (2 unidades)', calorias: 240, proteinas: 10, carbohidratos: 36, porcion: '2 panqueques' },
  { categoria: 'Desayuno / Lácteos', nombre: 'Yogur griego (poco / 2 cucharadas)', calorias: 45, proteinas: 4, carbohidratos: 2, porcion: '2 cucharadas' },
  { categoria: 'Desayuno / Lácteos', nombre: 'Queso fresco (porción)', calorias: 75, proteinas: 5, carbohidratos: 1, porcion: '30 g' },
  { categoria: 'Desayuno / Lácteos', nombre: 'Queso curado (2 lonchas)', calorias: 100, proteinas: 7, carbohidratos: 0.5, porcion: '2 lonchas' },
  { categoria: 'Desayuno / Lácteos', nombre: 'Mantequilla (1 porción)', calorias: 100, proteinas: 0, carbohidratos: 0, porcion: '1 cucharada 10 g' },
  { categoria: 'Desayuno / Lácteos', nombre: 'Mermelada (1 cucharada)', calorias: 50, proteinas: 0, carbohidratos: 13, porcion: '1 cucharada' },
  { categoria: 'Desayuno / Lácteos', nombre: 'Miel (1 cucharada)', calorias: 60, proteinas: 0, carbohidratos: 17, porcion: '1 cucharada' },
  { categoria: 'Desayuno / Lácteos', nombre: 'Crema de cacahuete (1 cucharada)', calorias: 95, proteinas: 4, carbohidratos: 3, porcion: '1 cucharada' },
  { categoria: 'Desayuno / Lácteos', nombre: 'Smoothie de frutas (1 vaso)', calorias: 150, proteinas: 2, carbohidratos: 35, porcion: '1 vaso' },
  { categoria: 'Desayuno / Lácteos', nombre: 'Granola (1/2 taza)', calorias: 230, proteinas: 5, carbohidratos: 43, porcion: '1/2 taza' },
  { categoria: 'Desayuno / Lácteos', nombre: 'Chía (1 cucharada)', calorias: 60, proteinas: 2, carbohidratos: 5, porcion: '1 cucharada' },

  // Lácteos y quesos (más opciones)
  { categoria: 'Lácteos y quesos', nombre: 'Leche semidesnatada (1 vaso)', calorias: 110, proteinas: 8, carbohidratos: 12, porcion: '250 ml' },
  { categoria: 'Lácteos y quesos', nombre: 'Leche condensada (2 cucharadas)', calorias: 130, proteinas: 3, carbohidratos: 22, porcion: '2 cucharadas' },
  { categoria: 'Lácteos y quesos', nombre: 'Leche evaporada (1/4 taza)', calorias: 80, proteinas: 4, carbohidratos: 6, porcion: '60 ml' },
  { categoria: 'Lácteos y quesos', nombre: 'Nata / crema de leche (2 cucharadas)', calorias: 100, proteinas: 0.5, carbohidratos: 1, porcion: '30 ml' },
  { categoria: 'Lácteos y quesos', nombre: 'Crema agria / sour cream (2 cucharadas)', calorias: 60, proteinas: 0.5, carbohidratos: 1, porcion: '30 g' },
  { categoria: 'Lácteos y quesos', nombre: 'Ricotta (1/2 taza)', calorias: 170, proteinas: 14, carbohidratos: 6, porcion: '1/2 taza' },
  { categoria: 'Lácteos y quesos', nombre: 'Queso mozzarella (1 bola 125 g)', calorias: 280, proteinas: 28, carbohidratos: 4, porcion: '125 g' },
  { categoria: 'Lácteos y quesos', nombre: 'Queso parmesano rallado (2 cucharadas)', calorias: 85, proteinas: 8, carbohidratos: 1, porcion: '20 g' },
  { categoria: 'Lácteos y quesos', nombre: 'Queso untable (2 cucharadas)', calorias: 100, proteinas: 4, carbohidratos: 2, porcion: '30 g' },
  { categoria: 'Lácteos y quesos', nombre: 'Queso azul / roquefort (30 g)', calorias: 105, proteinas: 6, carbohidratos: 1, porcion: '30 g' },
  { categoria: 'Lácteos y quesos', nombre: 'Queso gouda (2 cubos)', calorias: 140, proteinas: 10, carbohidratos: 1, porcion: '40 g' },
  { categoria: 'Lácteos y quesos', nombre: 'Queso emmental (2 lonchas)', calorias: 130, proteinas: 10, carbohidratos: 0, porcion: '40 g' },
  { categoria: 'Lácteos y quesos', nombre: 'Burrata (1 unidad)', calorias: 260, proteinas: 12, carbohidratos: 4, porcion: '100 g' },
  { categoria: 'Lácteos y quesos', nombre: 'Mascarpone (2 cucharadas)', calorias: 120, proteinas: 2, carbohidratos: 2, porcion: '30 g' },
  { categoria: 'Lácteos y quesos', nombre: 'Kéfir (1 vaso)', calorias: 110, proteinas: 6, carbohidratos: 12, porcion: '250 ml' },
  { categoria: 'Lácteos y quesos', nombre: 'Skyr (1 unidad)', calorias: 110, proteinas: 15, carbohidratos: 8, porcion: '150 g' },
  { categoria: 'Lácteos y quesos', nombre: 'Batido lácteo / milkshake (1 vaso)', calorias: 320, proteinas: 10, carbohidratos: 48, porcion: '300 ml' },
  { categoria: 'Lácteos y quesos', nombre: 'Flan casero (1 unidad)', calorias: 180, proteinas: 6, carbohidratos: 28, porcion: '1 unidad' },
  { categoria: 'Lácteos y quesos', nombre: 'Dulce de leche (1 cucharada)', calorias: 65, proteinas: 1, carbohidratos: 12, porcion: '1 cucharada' },
  { categoria: 'Lácteos y quesos', nombre: 'Crema pastelera (2 cucharadas)', calorias: 90, proteinas: 2, carbohidratos: 10, porcion: '30 g' },

  // Proteínas
  { categoria: 'Proteínas', nombre: 'Pechuga de pollo (150 g)', calorias: 165, proteinas: 31, carbohidratos: 0, porcion: '150 g' },
  { categoria: 'Proteínas', nombre: 'Muslo de pollo (150 g)', calorias: 210, proteinas: 26, carbohidratos: 0, porcion: '150 g' },
  { categoria: 'Proteínas', nombre: 'Carne de res magra (150 g)', calorias: 225, proteinas: 32, carbohidratos: 0, porcion: '150 g' },
  { categoria: 'Proteínas', nombre: 'Pescado blanco (150 g)', calorias: 120, proteinas: 26, carbohidratos: 0, porcion: '150 g' },
  { categoria: 'Proteínas', nombre: 'Salmón (150 g)', calorias: 280, proteinas: 28, carbohidratos: 0, porcion: '150 g' },
  { categoria: 'Proteínas', nombre: 'Atún en lata al natural (1 lata)', calorias: 100, proteinas: 22, carbohidratos: 0, porcion: '1 lata 80 g escurrido' },
  { categoria: 'Proteínas', nombre: 'Jamón cocido (2 lonchas)', calorias: 60, proteinas: 10, carbohidratos: 1, porcion: '2 lonchas 50 g' },
  { categoria: 'Proteínas', nombre: 'Jamón serrano (2 lonchas)', calorias: 80, proteinas: 12, carbohidratos: 0, porcion: '2 lonchas 30 g' },
  { categoria: 'Proteínas', nombre: 'Tofu (100 g)', calorias: 75, proteinas: 8, carbohidratos: 2, porcion: '100 g' },
  { categoria: 'Proteínas', nombre: 'Lentejas cocidas (1 taza)', calorias: 230, proteinas: 18, carbohidratos: 40, porcion: '1 taza' },
  { categoria: 'Proteínas', nombre: 'Garbanzos cocidos (1 taza)', calorias: 270, proteinas: 15, carbohidratos: 45, porcion: '1 taza' },
  { categoria: 'Proteínas', nombre: 'Alubias cocidas (1 taza)', calorias: 225, proteinas: 15, carbohidratos: 40, porcion: '1 taza' },
  { categoria: 'Proteínas', nombre: 'Hamburguesa de pollo (1 unidad)', calorias: 250, proteinas: 18, carbohidratos: 15, porcion: '1 unidad' },
  { categoria: 'Proteínas', nombre: 'Hamburguesa de res (1 unidad)', calorias: 350, proteinas: 20, carbohidratos: 25, porcion: '1 unidad' },
  { categoria: 'Proteínas', nombre: 'Pavo (pechuga 150 g)', calorias: 165, proteinas: 30, carbohidratos: 0, porcion: '150 g' },
  { categoria: 'Proteínas', nombre: 'Lomo de cerdo (150 g)', calorias: 250, proteinas: 28, carbohidratos: 0, porcion: '150 g' },
  { categoria: 'Proteínas', nombre: 'Costilla de cerdo (porción)', calorias: 350, proteinas: 25, carbohidratos: 0, porcion: '1 porción' },
  { categoria: 'Proteínas', nombre: 'Camarones (100 g)', calorias: 100, proteinas: 24, carbohidratos: 0.5, porcion: '100 g' },
  { categoria: 'Proteínas', nombre: 'Calamares (100 g)', calorias: 95, proteinas: 18, carbohidratos: 3, porcion: '100 g' },
  { categoria: 'Proteínas', nombre: 'Huevos revueltos con queso (2 huevos)', calorias: 250, proteinas: 16, carbohidratos: 2, porcion: '2 huevos' },
  { categoria: 'Proteínas', nombre: 'Tempeh (100 g)', calorias: 195, proteinas: 20, carbohidratos: 9, porcion: '100 g' },
  { categoria: 'Proteínas', nombre: 'Edamame (1 taza)', calorias: 190, proteinas: 17, carbohidratos: 15, porcion: '1 taza' },
  { categoria: 'Proteínas', nombre: 'Hummus (2 cucharadas)', calorias: 70, proteinas: 2, carbohidratos: 6, porcion: '2 cucharadas' },

  // Milanesas y rebozados (nombre explícito: pollo, carne, etc.; no “milanesa sola”)
  { categoria: 'Milanesas y rebozados', nombre: 'Milanesa de pollo (1 unidad rebozada)', calorias: 380, proteinas: 32, carbohidratos: 18, porcion: '~150 g' },
  { categoria: 'Milanesas y rebozados', nombre: 'Milanesa de carne / ternera (1 unidad)', calorias: 430, proteinas: 35, carbohidratos: 16, porcion: '~150 g' },
  { categoria: 'Milanesas y rebozados', nombre: 'Milanesa de cerdo (1 unidad)', calorias: 400, proteinas: 33, carbohidratos: 17, porcion: '~150 g' },
  { categoria: 'Milanesas y rebozados', nombre: 'Milanesa de merluza / pescado (1 unidad)', calorias: 290, proteinas: 28, carbohidratos: 21, porcion: '~150 g' },
  { categoria: 'Milanesas y rebozados', nombre: 'Milanesa de soja / vegetal (1 unidad)', calorias: 220, proteinas: 14, carbohidratos: 22, porcion: '~120 g' },
  { categoria: 'Milanesas y rebozados', nombre: 'Suprema de pollo a la milanesa (1 grande)', calorias: 450, proteinas: 36, carbohidratos: 20, porcion: '~200 g' },
  { categoria: 'Milanesas y rebozados', nombre: 'Milanesa napolitana de pollo (1 porción)', calorias: 540, proteinas: 38, carbohidratos: 30, porcion: 'jamón y queso' },
  { categoria: 'Milanesas y rebozados', nombre: 'Milanesa napolitana de carne (1 porción)', calorias: 580, proteinas: 40, carbohidratos: 28, porcion: 'jamón y queso' },
  { categoria: 'Milanesas y rebozados', nombre: 'Milanesa a la provenzal (1 unidad)', calorias: 410, proteinas: 33, carbohidratos: 19, porcion: '1 unidad' },
  { categoria: 'Milanesas y rebozados', nombre: 'Milanesa con puré (1 plato)', calorias: 590, proteinas: 36, carbohidratos: 50, porcion: '1 plato' },
  { categoria: 'Milanesas y rebozados', nombre: 'Milanesa con papas fritas (1 plato)', calorias: 730, proteinas: 34, carbohidratos: 64, porcion: '1 plato' },
  { categoria: 'Milanesas y rebozados', nombre: 'Escalope de pollo empanado (1 unidad)', calorias: 360, proteinas: 30, carbohidratos: 20, porcion: '1 unidad' },
  { categoria: 'Milanesas y rebozados', nombre: 'Pollo rebozado / empanado (2 filetes medianos)', calorias: 520, proteinas: 40, carbohidratos: 34, porcion: '2 unid' },

  // Fiambres y embutidos (lonchas típicas)
  { categoria: 'Fiambres', nombre: 'Salame (4 lonchas)', calorias: 180, proteinas: 10, carbohidratos: 1, porcion: '40 g' },
  { categoria: 'Fiambres', nombre: 'Mortadela (2 lonchas)', calorias: 140, proteinas: 8, carbohidratos: 2, porcion: '50 g' },
  { categoria: 'Fiambres', nombre: 'Pechito de pavo (2 lonchas)', calorias: 55, proteinas: 10, carbohidratos: 1, porcion: '50 g' },
  { categoria: 'Fiambres', nombre: 'Fiambre de pollo (2 lonchas)', calorias: 70, proteinas: 11, carbohidratos: 2, porcion: '50 g' },
  { categoria: 'Fiambres', nombre: 'Bondiola cocida (2 lonchas)', calorias: 120, proteinas: 14, carbohidratos: 1, porcion: '50 g' },
  { categoria: 'Fiambres', nombre: 'Lomito embuchado (2 lonchas)', calorias: 100, proteinas: 12, carbohidratos: 1, porcion: '50 g' },
  { categoria: 'Fiambres', nombre: 'Pastrón / pastrami (2 lonchas)', calorias: 110, proteinas: 14, carbohidratos: 2, porcion: '50 g' },
  { categoria: 'Fiambres', nombre: 'Panceta ahumada (2 lonchas)', calorias: 180, proteinas: 8, carbohidratos: 0, porcion: '40 g' },
  { categoria: 'Fiambres', nombre: 'Bacon (3 tiras)', calorias: 130, proteinas: 9, carbohidratos: 0, porcion: '30 g' },
  { categoria: 'Fiambres', nombre: 'Chorizo colorado / fiambrería (2 lonchas)', calorias: 160, proteinas: 8, carbohidratos: 2, porcion: '50 g' },
  { categoria: 'Fiambres', nombre: 'Morcilla (1 unidad asada)', calorias: 220, proteinas: 10, carbohidratos: 8, porcion: '1 unidad' },
  { categoria: 'Fiambres', nombre: 'Jamón crudo / serrano (4 lonchas)', calorias: 120, proteinas: 16, carbohidratos: 0, porcion: '40 g' },
  { categoria: 'Fiambres', nombre: 'Jamón york / dulce (2 lonchas)', calorias: 60, proteinas: 10, carbohidratos: 1, porcion: '50 g' },
  { categoria: 'Fiambres', nombre: 'Queso en lonchas tipo cheddar (2 lonchas)', calorias: 140, proteinas: 8, carbohidratos: 1, porcion: '40 g' },
  { categoria: 'Fiambres', nombre: 'Queso en lonchas light (2 lonchas)', calorias: 80, proteinas: 10, carbohidratos: 1, porcion: '40 g' },

  // Carbohidratos
  { categoria: 'Carbohidratos', nombre: 'Arroz blanco cocido (1 taza)', calorias: 240, proteinas: 4, carbohidratos: 53, porcion: '1 taza' },
  { categoria: 'Carbohidratos', nombre: 'Arroz integral cocido (1 taza)', calorias: 215, proteinas: 5, carbohidratos: 45, porcion: '1 taza' },
  { categoria: 'Carbohidratos', nombre: 'Pasta cocida (1 taza)', calorias: 220, proteinas: 8, carbohidratos: 43, porcion: '1 taza' },
  { categoria: 'Carbohidratos', nombre: 'Patata cocida (1 mediana)', calorias: 130, proteinas: 2, carbohidratos: 30, porcion: '1 patata mediana' },
  { categoria: 'Carbohidratos', nombre: 'Patatas fritas (porción)', calorias: 350, proteinas: 4, carbohidratos: 45, porcion: 'porción mediana' },
  { categoria: 'Carbohidratos', nombre: 'Pan integral (2 rebanadas)', calorias: 160, proteinas: 8, carbohidratos: 28, porcion: '2 rebanadas' },
  { categoria: 'Carbohidratos', nombre: 'Quinoa cocida (1 taza)', calorias: 220, proteinas: 8, carbohidratos: 39, porcion: '1 taza' },
  { categoria: 'Carbohidratos', nombre: 'Batata cocida (1 mediana)', calorias: 130, proteinas: 2, carbohidratos: 30, porcion: '1 batata' },
  { categoria: 'Carbohidratos', nombre: 'Couscous (1 taza)', calorias: 175, proteinas: 6, carbohidratos: 36, porcion: '1 taza' },
  { categoria: 'Carbohidratos', nombre: 'Tortilla de trigo (1 unidad)', calorias: 160, proteinas: 4, carbohidratos: 27, porcion: '1 tortilla' },
  { categoria: 'Carbohidratos', nombre: 'Pan de centeno (1 rebanada)', calorias: 80, proteinas: 3, carbohidratos: 15, porcion: '1 rebanada' },
  { categoria: 'Carbohidratos', nombre: 'Pan de molde (1 rebanada)', calorias: 70, proteinas: 2, carbohidratos: 13, porcion: '1 rebanada' },
  { categoria: 'Carbohidratos', nombre: 'Muesli (1 taza)', calorias: 290, proteinas: 8, carbohidratos: 66, porcion: '1 taza' },
  { categoria: 'Carbohidratos', nombre: 'Arepa (1 unidad)', calorias: 150, proteinas: 3, carbohidratos: 30, porcion: '1 arepa' },
  { categoria: 'Carbohidratos', nombre: 'Empanada (1 unidad)', calorias: 280, proteinas: 8, carbohidratos: 28, porcion: '1 empanada' },
  { categoria: 'Carbohidratos', nombre: 'Ñoquis (1 taza)', calorias: 250, proteinas: 6, carbohidratos: 48, porcion: '1 taza' },
  { categoria: 'Carbohidratos', nombre: 'Polenta (1 taza)', calorias: 145, proteinas: 3, carbohidratos: 31, porcion: '1 taza' },
  { categoria: 'Carbohidratos', nombre: 'Arroz blanco solo (1/2 taza)', calorias: 120, proteinas: 2, carbohidratos: 26, porcion: '1/2 taza cocido' },
  { categoria: 'Carbohidratos', nombre: 'Arroz amarillo / con verduras (1 taza)', calorias: 260, proteinas: 5, carbohidratos: 52, porcion: '1 taza' },
  { categoria: 'Carbohidratos', nombre: 'Arroz primavera (1 taza)', calorias: 250, proteinas: 6, carbohidratos: 48, porcion: '1 taza' },
  { categoria: 'Carbohidratos', nombre: 'Arroz frito (1 taza)', calorias: 320, proteinas: 8, carbohidratos: 52, porcion: '1 taza' },
  { categoria: 'Carbohidratos', nombre: 'Arroz negro / con tinta (1 taza)', calorias: 260, proteinas: 8, carbohidratos: 48, porcion: '1 taza' },
  { categoria: 'Carbohidratos', nombre: 'Arroz con leche (1 bowl)', calorias: 280, proteinas: 8, carbohidratos: 48, porcion: '1 bowl' },
  { categoria: 'Carbohidratos', nombre: 'Arroz al horno (1 porción)', calorias: 320, proteinas: 10, carbohidratos: 48, porcion: '1 porción' },
  { categoria: 'Carbohidratos', nombre: 'Arroz basmati cocido (1 taza)', calorias: 235, proteinas: 4, carbohidratos: 51, porcion: '1 taza' },
  { categoria: 'Carbohidratos', nombre: 'Arroz parbolizado (1 taza)', calorias: 230, proteinas: 4, carbohidratos: 50, porcion: '1 taza' },
  { categoria: 'Carbohidratos', nombre: 'Arroz con queso (1 taza)', calorias: 300, proteinas: 10, carbohidratos: 48, porcion: '1 taza' },
  { categoria: 'Carbohidratos', nombre: 'Fideos secos crudos (80 g)', calorias: 280, proteinas: 10, carbohidratos: 56, porcion: '80 g secos' },
  { categoria: 'Carbohidratos', nombre: 'Fideos integrales cocidos (1 taza)', calorias: 210, proteinas: 8, carbohidratos: 41, porcion: '1 taza' },
  { categoria: 'Carbohidratos', nombre: 'Fideos sin gluten cocidos (1 taza)', calorias: 200, proteinas: 4, carbohidratos: 44, porcion: '1 taza' },
  { categoria: 'Carbohidratos', nombre: 'Mostacholes cocidos (1 taza)', calorias: 220, proteinas: 8, carbohidratos: 43, porcion: '1 taza' },
  { categoria: 'Carbohidratos', nombre: 'Coditos / codos (1 taza)', calorias: 220, proteinas: 8, carbohidratos: 43, porcion: '1 taza' },
  { categoria: 'Carbohidratos', nombre: 'Tallarines / fideos al huevo (1 taza)', calorias: 225, proteinas: 8, carbohidratos: 42, porcion: '1 taza' },
  { categoria: 'Carbohidratos', nombre: 'Fideos con manteca (1 plato)', calorias: 320, proteinas: 9, carbohidratos: 48, porcion: '1 plato' },

  // Pastas (variedades y platos)
  { categoria: 'Pastas', nombre: 'Fideos (1 taza cocidos)', calorias: 220, proteinas: 8, carbohidratos: 43, porcion: '1 taza' },
  { categoria: 'Pastas', nombre: 'Spaghetti (1 taza)', calorias: 220, proteinas: 8, carbohidratos: 43, porcion: '1 taza' },
  { categoria: 'Pastas', nombre: 'Tallarines (1 taza)', calorias: 220, proteinas: 8, carbohidratos: 43, porcion: '1 taza' },
  { categoria: 'Pastas', nombre: 'Penne (1 taza)', calorias: 220, proteinas: 8, carbohidratos: 43, porcion: '1 taza' },
  { categoria: 'Pastas', nombre: 'Macarrones (1 taza)', calorias: 220, proteinas: 8, carbohidratos: 43, porcion: '1 taza' },
  { categoria: 'Pastas', nombre: 'Ravioles (6-8 unidades)', calorias: 280, proteinas: 12, carbohidratos: 42, porcion: '6-8 unid' },
  { categoria: 'Pastas', nombre: 'Canelones (2 unidades)', calorias: 350, proteinas: 18, carbohidratos: 38, porcion: '2 canelones' },
  { categoria: 'Pastas', nombre: 'Fetuccini (1 taza)', calorias: 230, proteinas: 8, carbohidratos: 44, porcion: '1 taza' },
  { categoria: 'Pastas', nombre: 'Rigatoni (1 taza)', calorias: 220, proteinas: 8, carbohidratos: 43, porcion: '1 taza' },
  { categoria: 'Pastas', nombre: 'Lasagna (1 porción)', calorias: 400, proteinas: 22, carbohidratos: 38, porcion: '1 porción' },
  { categoria: 'Pastas', nombre: 'Pasta con salsa de tomate (1 plato)', calorias: 380, proteinas: 12, carbohidratos: 65, porcion: '1 plato' },
  { categoria: 'Pastas', nombre: 'Pasta con boloñesa (1 plato)', calorias: 480, proteinas: 24, carbohidratos: 58, porcion: '1 plato' },
  { categoria: 'Pastas', nombre: 'Pasta con pesto (1 plato)', calorias: 520, proteinas: 14, carbohidratos: 48, porcion: '1 plato' },
  { categoria: 'Pastas', nombre: 'Pasta con salsa blanca (1 plato)', calorias: 450, proteinas: 14, carbohidratos: 52, porcion: '1 plato' },
  { categoria: 'Pastas', nombre: 'Fideos con tuco (1 plato)', calorias: 400, proteinas: 14, carbohidratos: 60, porcion: '1 plato' },
  { categoria: 'Pastas', nombre: 'Sopa de fideos (1 bowl)', calorias: 180, proteinas: 6, carbohidratos: 32, porcion: '1 bowl' },
  { categoria: 'Pastas', nombre: 'Ñoquis con tuco (1 plato)', calorias: 420, proteinas: 14, carbohidratos: 62, porcion: '1 plato' },
  { categoria: 'Pastas', nombre: 'Ñoquis con salsa blanca', calorias: 450, proteinas: 12, carbohidratos: 65, porcion: '1 plato' },
  { categoria: 'Pastas', nombre: 'Tallarines saltados (1 plato)', calorias: 450, proteinas: 18, carbohidratos: 55, porcion: '1 plato' },
  { categoria: 'Pastas', nombre: 'Sorrentinos (4-5 unidades)', calorias: 350, proteinas: 16, carbohidratos: 42, porcion: '4-5 unid' },
  { categoria: 'Pastas', nombre: 'Capeletis (1 porción)', calorias: 320, proteinas: 14, carbohidratos: 45, porcion: '1 porción' },
  { categoria: 'Pastas', nombre: 'Tirabuzón / fusilli (1 taza)', calorias: 220, proteinas: 8, carbohidratos: 43, porcion: '1 taza' },
  { categoria: 'Pastas', nombre: 'Ditalini / mostacilla (1 taza)', calorias: 220, proteinas: 8, carbohidratos: 43, porcion: '1 taza' },
  { categoria: 'Pastas', nombre: 'Lasaña de carne (1 porción)', calorias: 420, proteinas: 24, carbohidratos: 36, porcion: '1 porción' },
  { categoria: 'Pastas', nombre: 'Canelones de verdura (2 unidades)', calorias: 320, proteinas: 14, carbohidratos: 40, porcion: '2 unid' },
  { categoria: 'Pastas', nombre: 'Fideos moños / moñitos (1 taza)', calorias: 220, proteinas: 8, carbohidratos: 43, porcion: '1 taza' },
  { categoria: 'Pastas', nombre: 'Espaguetis integrales (1 taza)', calorias: 210, proteinas: 8, carbohidratos: 41, porcion: '1 taza' },
  { categoria: 'Pastas', nombre: 'Pasta rellena de ricota (4 unidades)', calorias: 300, proteinas: 14, carbohidratos: 38, porcion: '4 unid' },

  // Almuerzo / Comidas completas
  { categoria: 'Almuerzo', nombre: 'Arroz con pollo (1 plato)', calorias: 480, proteinas: 32, carbohidratos: 52, porcion: '1 plato' },
  { categoria: 'Almuerzo', nombre: 'Arroz con carne (1 plato)', calorias: 520, proteinas: 28, carbohidratos: 55, porcion: '1 plato' },
  { categoria: 'Almuerzo', nombre: 'Arroz con huevo (1 plato)', calorias: 380, proteinas: 14, carbohidratos: 52, porcion: '1 plato' },
  { categoria: 'Almuerzo', nombre: 'Arroz con mariscos (1 plato)', calorias: 450, proteinas: 26, carbohidratos: 50, porcion: '1 plato' },
  { categoria: 'Almuerzo', nombre: 'Bife con puré (1 plato)', calorias: 520, proteinas: 38, carbohidratos: 42, porcion: '1 plato' },
  { categoria: 'Almuerzo', nombre: 'Pollo al horno con papas (1 plato)', calorias: 550, proteinas: 40, carbohidratos: 48, porcion: '1 plato' },
  { categoria: 'Almuerzo', nombre: 'Pescado con arroz (1 plato)', calorias: 420, proteinas: 32, carbohidratos: 48, porcion: '1 plato' },
  { categoria: 'Almuerzo', nombre: 'Estofado de carne (1 plato)', calorias: 450, proteinas: 35, carbohidratos: 28, porcion: '1 plato' },
  { categoria: 'Almuerzo', nombre: 'Locro (1 bowl)', calorias: 380, proteinas: 18, carbohidratos: 45, porcion: '1 bowl' },
  { categoria: 'Almuerzo', nombre: 'Carbonada (1 bowl)', calorias: 400, proteinas: 22, carbohidratos: 42, porcion: '1 bowl' },
  { categoria: 'Almuerzo', nombre: 'Sopa de pollo (1 bowl)', calorias: 220, proteinas: 22, carbohidratos: 18, porcion: '1 bowl' },
  { categoria: 'Almuerzo', nombre: 'Caldo de verduras (1 taza)', calorias: 60, proteinas: 2, carbohidratos: 10, porcion: '1 taza' },
  { categoria: 'Almuerzo', nombre: 'Crema de calabaza (1 bowl)', calorias: 180, proteinas: 4, carbohidratos: 28, porcion: '1 bowl' },
  { categoria: 'Almuerzo', nombre: 'Ensalada rusa (1 porción)', calorias: 220, proteinas: 4, carbohidratos: 25, porcion: '1 porción' },
  { categoria: 'Almuerzo', nombre: 'Ensalada de pasta (1 plato)', calorias: 380, proteinas: 12, carbohidratos: 52, porcion: '1 plato' },
  { categoria: 'Almuerzo', nombre: 'Lomito / sandwich de lomo (1 unidad)', calorias: 520, proteinas: 32, carbohidratos: 42, porcion: '1 unidad' },
  { categoria: 'Almuerzo', nombre: 'Choripán (1 unidad)', calorias: 380, proteinas: 16, carbohidratos: 35, porcion: '1 unidad' },
  { categoria: 'Almuerzo', nombre: 'Churrasco con ensalada (1 plato)', calorias: 420, proteinas: 38, carbohidratos: 12, porcion: '1 plato' },
  { categoria: 'Almuerzo', nombre: 'Pechuga a la plancha con vegetales (1 plato)', calorias: 350, proteinas: 42, carbohidratos: 18, porcion: '1 plato' },
  { categoria: 'Almuerzo', nombre: 'Pollo a la parrilla con ensalada (1 plato)', calorias: 380, proteinas: 40, carbohidratos: 15, porcion: '1 plato' },
  { categoria: 'Almuerzo', nombre: 'Merluza con puré (1 plato)', calorias: 380, proteinas: 32, carbohidratos: 35, porcion: '1 plato' },
  { categoria: 'Almuerzo', nombre: 'Huevos con arroz (1 plato)', calorias: 400, proteinas: 18, carbohidratos: 50, porcion: '1 plato' },
  { categoria: 'Almuerzo', nombre: 'Lentejas con arroz (1 plato)', calorias: 420, proteinas: 20, carbohidratos: 68, porcion: '1 plato' },
  { categoria: 'Almuerzo', nombre: 'Porotos con rienda (1 plato)', calorias: 380, proteinas: 18, carbohidratos: 52, porcion: '1 plato' },
  { categoria: 'Almuerzo', nombre: 'Cazuela de vacuno (1 bowl)', calorias: 350, proteinas: 32, carbohidratos: 22, porcion: '1 bowl' },
  { categoria: 'Almuerzo', nombre: 'Pollo al disco (1 porción)', calorias: 450, proteinas: 36, carbohidratos: 28, porcion: '1 porción' },
  { categoria: 'Almuerzo', nombre: 'Pastel de choclo (1 porción)', calorias: 420, proteinas: 22, carbohidratos: 45, porcion: '1 porción' },
  { categoria: 'Almuerzo', nombre: 'Humita (1 unidad)', calorias: 280, proteinas: 10, carbohidratos: 42, porcion: '1 unidad' },
  { categoria: 'Almuerzo', nombre: 'Tamal (1 unidad)', calorias: 350, proteinas: 14, carbohidratos: 42, porcion: '1 unidad' },
  { categoria: 'Almuerzo', nombre: 'Pollo con curry y arroz (1 plato)', calorias: 480, proteinas: 34, carbohidratos: 52, porcion: '1 plato' },
  { categoria: 'Almuerzo', nombre: 'Salteado de verduras con pollo (1 plato)', calorias: 320, proteinas: 30, carbohidratos: 22, porcion: '1 plato' },
  { categoria: 'Almuerzo', nombre: 'Carne al jugo con papas (1 plato)', calorias: 500, proteinas: 36, carbohidratos: 38, porcion: '1 plato' },
  { categoria: 'Almuerzo', nombre: 'Guiso de lentejas (1 plato)', calorias: 400, proteinas: 22, carbohidratos: 55, porcion: '1 plato' },
  { categoria: 'Almuerzo', nombre: 'Guiso de arroz (1 plato)', calorias: 380, proteinas: 14, carbohidratos: 58, porcion: '1 plato' },
  { categoria: 'Almuerzo', nombre: 'Pollo relleno con puré (1 porción)', calorias: 480, proteinas: 38, carbohidratos: 42, porcion: '1 porción' },
  { categoria: 'Almuerzo', nombre: 'Berenjena rellena (1 unidad)', calorias: 280, proteinas: 14, carbohidratos: 28, porcion: '1 unidad' },
  { categoria: 'Almuerzo', nombre: 'Calabacín relleno (1 unidad)', calorias: 220, proteinas: 12, carbohidratos: 22, porcion: '1 unidad' },
  { categoria: 'Almuerzo', nombre: 'Tortilla de verduras (1 porción)', calorias: 200, proteinas: 12, carbohidratos: 15, porcion: '1 porción' },
  { categoria: 'Almuerzo', nombre: 'Revuelto de verduras con arroz (1 plato)', calorias: 350, proteinas: 14, carbohidratos: 48, porcion: '1 plato' },
  { categoria: 'Almuerzo', nombre: 'Pescado al horno con verduras (1 plato)', calorias: 320, proteinas: 35, carbohidratos: 18, porcion: '1 plato' },
  { categoria: 'Almuerzo', nombre: 'Bocadillo de tortilla (1 unidad)', calorias: 420, proteinas: 22, carbohidratos: 45, porcion: '1 unidad' },
  { categoria: 'Almuerzo', nombre: 'Medialunas con jamón y queso (2 unid)', calorias: 380, proteinas: 14, carbohidratos: 42, porcion: '2 unid' },
  { categoria: 'Almuerzo', nombre: 'Tostado / sandwich tostado (1 unidad)', calorias: 320, proteinas: 16, carbohidratos: 35, porcion: '1 unidad' },
  { categoria: 'Almuerzo', nombre: 'Pan con milanesa (1 unidad)', calorias: 480, proteinas: 28, carbohidratos: 42, porcion: '1 unidad' },
  { categoria: 'Almuerzo', nombre: 'Ensalada de atún (1 plato)', calorias: 280, proteinas: 30, carbohidratos: 12, porcion: '1 plato' },
  { categoria: 'Almuerzo', nombre: 'Ensalada de pollo (1 plato)', calorias: 320, proteinas: 32, carbohidratos: 15, porcion: '1 plato' },
  { categoria: 'Almuerzo', nombre: 'Wok de verduras con carne (1 plato)', calorias: 380, proteinas: 28, carbohidratos: 28, porcion: '1 plato' },
  { categoria: 'Almuerzo', nombre: 'Arroz chaufa (1 plato)', calorias: 450, proteinas: 20, carbohidratos: 52, porcion: '1 plato' },
  { categoria: 'Almuerzo', nombre: 'Tallarín saltado (1 plato)', calorias: 480, proteinas: 22, carbohidratos: 55, porcion: '1 plato' },
  { categoria: 'Almuerzo', nombre: 'Aeropuerto / arroz con tallarín (1 plato)', calorias: 460, proteinas: 18, carbohidratos: 58, porcion: '1 plato' },

  // Verduras y ensaladas
  { categoria: 'Verduras', nombre: 'Ensalada verde (1 plato)', calorias: 50, proteinas: 3, carbohidratos: 8, porcion: '1 plato' },
  { categoria: 'Verduras', nombre: 'Brócoli cocido (1 taza)', calorias: 55, proteinas: 4, carbohidratos: 11, porcion: '1 taza' },
  { categoria: 'Verduras', nombre: 'Zanahoria (1 unidad)', calorias: 25, proteinas: 0.5, carbohidratos: 6, porcion: '1 zanahoria' },
  { categoria: 'Verduras', nombre: 'Tomate (1 unidad)', calorias: 22, proteinas: 1, carbohidratos: 5, porcion: '1 tomate' },
  { categoria: 'Verduras', nombre: 'Pepino (1/2 unidad)', calorias: 15, proteinas: 0.5, carbohidratos: 4, porcion: 'medio pepino' },
  { categoria: 'Verduras', nombre: 'Espinacas cocidas (1 taza)', calorias: 40, proteinas: 5, carbohidratos: 6, porcion: '1 taza' },
  { categoria: 'Verduras', nombre: 'Pimiento (1/2 unidad)', calorias: 20, proteinas: 1, carbohidratos: 5, porcion: 'medio pimiento' },
  { categoria: 'Verduras', nombre: 'Guisantes cocidos (1 taza)', calorias: 125, proteinas: 8, carbohidratos: 22, porcion: '1 taza' },
  { categoria: 'Verduras', nombre: 'Maíz (1 taza)', calorias: 130, proteinas: 4, carbohidratos: 28, porcion: '1 taza' },
  { categoria: 'Verduras', nombre: 'Calabacín (1/2 unidad)', calorias: 15, proteinas: 1, carbohidratos: 3, porcion: 'medio calabacín' },
  { categoria: 'Verduras', nombre: 'Berenjena (1/2 unidad)', calorias: 20, proteinas: 0.8, carbohidratos: 5, porcion: 'media berenjena' },
  { categoria: 'Verduras', nombre: 'Coliflor (1 taza)', calorias: 25, proteinas: 2, carbohidratos: 5, porcion: '1 taza' },
  { categoria: 'Verduras', nombre: 'Col rizada / kale (1 taza)', calorias: 35, proteinas: 3, carbohidratos: 4, porcion: '1 taza' },
  { categoria: 'Verduras', nombre: 'Lechuga (1 taza)', calorias: 8, proteinas: 0.5, carbohidratos: 1.5, porcion: '1 taza' },
  { categoria: 'Verduras', nombre: 'Rúcula (1 taza)', calorias: 5, proteinas: 0.5, carbohidratos: 0.7, porcion: '1 taza' },
  { categoria: 'Verduras', nombre: 'Remolacha (1 unidad)', calorias: 60, proteinas: 2, carbohidratos: 13, porcion: '1 remolacha' },
  { categoria: 'Verduras', nombre: 'Cebolla (1/2 unidad)', calorias: 25, proteinas: 0.5, carbohidratos: 6, porcion: 'media cebolla' },
  { categoria: 'Verduras', nombre: 'Champiñones / hongos comunes (1 taza)', calorias: 15, proteinas: 2, carbohidratos: 2, porcion: '1 taza' },
  { categoria: 'Verduras', nombre: 'Champiñones portobello (1 unidad)', calorias: 25, proteinas: 2.5, carbohidratos: 4, porcion: '1 grande' },
  { categoria: 'Verduras', nombre: 'Setas / shiitake (1 taza)', calorias: 35, proteinas: 2.5, carbohidratos: 7, porcion: '1 taza' },
  { categoria: 'Verduras', nombre: 'Hongos salteados (1 taza)', calorias: 80, proteinas: 3, carbohidratos: 6, porcion: 'con aceite' },
  { categoria: 'Verduras', nombre: 'Judías verdes (1 taza)', calorias: 35, proteinas: 2, carbohidratos: 8, porcion: '1 taza' },
  { categoria: 'Verduras', nombre: 'Alcachofa (1 unidad)', calorias: 60, proteinas: 4, carbohidratos: 13, porcion: '1 alcachofa' },
  { categoria: 'Verduras', nombre: 'Apio (1 tallo)', calorias: 6, proteinas: 0.3, carbohidratos: 1, porcion: '1 tallo' },
  { categoria: 'Verduras', nombre: 'Calabaza (1 taza)', calorias: 50, proteinas: 2, carbohidratos: 12, porcion: '1 taza' },
  { categoria: 'Verduras', nombre: 'Acelga cocida (1 taza)', calorias: 35, proteinas: 3, carbohidratos: 5, porcion: '1 taza' },
  { categoria: 'Verduras', nombre: 'Espinaca cruda (1 taza)', calorias: 10, proteinas: 1, carbohidratos: 1.5, porcion: '1 taza' },
  { categoria: 'Verduras', nombre: 'Radicheta / rúcula picante (1 taza)', calorias: 8, proteinas: 0.8, carbohidratos: 1.2, porcion: '1 taza' },
  { categoria: 'Verduras', nombre: 'Endibia (1 unidad)', calorias: 8, proteinas: 0.5, carbohidratos: 2, porcion: '1 unidad' },
  { categoria: 'Verduras', nombre: 'Repollo / col blanca (1 taza)', calorias: 22, proteinas: 1, carbohidratos: 5, porcion: '1 taza' },
  { categoria: 'Verduras', nombre: 'Repollo morado (1 taza)', calorias: 28, proteinas: 1, carbohidratos: 7, porcion: '1 taza' },
  { categoria: 'Verduras', nombre: 'Kale / col rizada cruda (1 taza)', calorias: 35, proteinas: 2.5, carbohidratos: 4, porcion: '1 taza' },
  { categoria: 'Verduras', nombre: 'Hoja de mostaza (1 taza)', calorias: 15, proteinas: 1.5, carbohidratos: 2.5, porcion: '1 taza' },
  { categoria: 'Verduras', nombre: 'Pak choi / bok choy (1 taza)', calorias: 20, proteinas: 2, carbohidratos: 3, porcion: '1 taza' },
  { categoria: 'Verduras', nombre: 'Espárragos (6 unidades)', calorias: 20, proteinas: 2, carbohidratos: 4, porcion: '6 espárragos' },
  { categoria: 'Verduras', nombre: 'Puerro (1 unidad mediana)', calorias: 55, proteinas: 1.5, carbohidratos: 13, porcion: '1 puerro' },
  { categoria: 'Verduras', nombre: 'Nabo (1 unidad)', calorias: 35, proteinas: 1, carbohidratos: 8, porcion: '1 nabo' },
  { categoria: 'Verduras', nombre: 'Rábano (5 unidades)', calorias: 12, proteinas: 0.5, carbohidratos: 2.5, porcion: '5 rábanos' },
  { categoria: 'Verduras', nombre: 'Okra / quimbombó (1 taza)', calorias: 35, proteinas: 2, carbohidratos: 8, porcion: '1 taza' },
  { categoria: 'Verduras', nombre: 'Vainitas / ejotes (1 taza)', calorias: 40, proteinas: 2, carbohidratos: 9, porcion: '1 taza' },
  { categoria: 'Verduras', nombre: 'Brotes de soja (1 taza)', calorias: 85, proteinas: 9, carbohidratos: 7, porcion: '1 taza' },
  { categoria: 'Verduras', nombre: 'Brotes de alfalfa (1 taza)', calorias: 20, proteinas: 2, carbohidratos: 2, porcion: '1 taza' },
  { categoria: 'Verduras', nombre: 'Palmitos (4 unidades)', calorias: 20, proteinas: 1.5, carbohidratos: 4, porcion: '4 rodajas' },
  { categoria: 'Verduras', nombre: 'Pickles / pepinillos (3 unidades)', calorias: 15, proteinas: 0.5, carbohidratos: 3, porcion: '3 unid' },
  { categoria: 'Verduras', nombre: 'Aceitunas verdes (10 unidades)', calorias: 50, proteinas: 0.5, carbohidratos: 2, porcion: '10 aceitunas' },
  { categoria: 'Verduras', nombre: 'Tomate cherry (15 unidades)', calorias: 30, proteinas: 1.5, carbohidratos: 6, porcion: '15 unid' },
  { categoria: 'Verduras', nombre: 'Zucchini / zapallito italiano (1 taza)', calorias: 20, proteinas: 1.5, carbohidratos: 4, porcion: '1 taza' },
  { categoria: 'Verduras', nombre: 'Batata asada (1/2 mediana)', calorias: 90, proteinas: 1, carbohidratos: 21, porcion: 'media batata' },
  { categoria: 'Verduras', nombre: 'Puré de papas (1/2 taza)', calorias: 120, proteinas: 2, carbohidratos: 18, porcion: '1/2 taza' },
  { categoria: 'Verduras', nombre: 'Puré de batata (1/2 taza)', calorias: 115, proteinas: 2, carbohidratos: 22, porcion: '1/2 taza' },
  { categoria: 'Verduras', nombre: 'Batata frita / chips (1 porción)', calorias: 180, proteinas: 2, carbohidratos: 28, porcion: '40 g' },
  { categoria: 'Verduras', nombre: 'Papa hervida (1 mediana)', calorias: 130, proteinas: 3, carbohidratos: 30, porcion: '1 papa' },
  { categoria: 'Verduras', nombre: 'Papa al horno (1 mediana)', calorias: 160, proteinas: 3, carbohidratos: 36, porcion: 'con piel' },
  { categoria: 'Verduras', nombre: 'Batata hervida (1/2 mediana)', calorias: 80, proteinas: 1, carbohidratos: 19, porcion: 'media' },
  { categoria: 'Verduras', nombre: 'Choclo / maíz en grano (1 taza)', calorias: 130, proteinas: 4, carbohidratos: 28, porcion: '1 taza' },
  { categoria: 'Verduras', nombre: 'Zapallo anco / calabaza (1 taza)', calorias: 45, proteinas: 1.5, carbohidratos: 10, porcion: '1 taza' },
  { categoria: 'Verduras', nombre: 'Hinojo (1 taza)', calorias: 25, proteinas: 1, carbohidratos: 6, porcion: '1 taza' },
  { categoria: 'Verduras', nombre: 'Ajo (3 dientes)', calorias: 15, proteinas: 0.6, carbohidratos: 3, porcion: '3 dientes' },
  { categoria: 'Verduras', nombre: 'Jengibre fresco (1 cucharada rallada)', calorias: 5, proteinas: 0.1, carbohidratos: 1, porcion: '1 cucharada' },
  { categoria: 'Verduras', nombre: 'Cilantro / perejil (1/2 taza picado)', calorias: 5, proteinas: 0.5, carbohidratos: 1, porcion: '1/2 taza' },
  { categoria: 'Verduras', nombre: 'Albahaca fresca (10 hojas)', calorias: 2, proteinas: 0.2, carbohidratos: 0.2, porcion: '10 hojas' },
  { categoria: 'Verduras', nombre: 'Orégano seco (1 cucharadita)', calorias: 5, proteinas: 0.2, carbohidratos: 1, porcion: '1 cdta' },
  { categoria: 'Verduras', nombre: 'Mix de verduras congeladas (1 taza)', calorias: 60, proteinas: 3, carbohidratos: 12, porcion: '1 taza' },

  // Frutas
  { categoria: 'Frutas', nombre: 'Plátano (1 unidad)', calorias: 105, proteinas: 1, carbohidratos: 27, porcion: '1 plátano' },
  { categoria: 'Frutas', nombre: 'Naranja (1 unidad)', calorias: 62, proteinas: 1, carbohidratos: 15, porcion: '1 naranja' },
  { categoria: 'Frutas', nombre: 'Uvas (1 taza)', calorias: 100, proteinas: 1, carbohidratos: 27, porcion: '1 taza' },
  { categoria: 'Frutas', nombre: 'Fresas (1 taza)', calorias: 50, proteinas: 1, carbohidratos: 12, porcion: '1 taza' },
  { categoria: 'Frutas', nombre: 'Manzana (1 unidad)', calorias: 95, proteinas: 0.5, carbohidratos: 25, porcion: '1 manzana' },
  { categoria: 'Frutas', nombre: 'Pera (1 unidad)', calorias: 100, proteinas: 0.5, carbohidratos: 27, porcion: '1 pera' },
  { categoria: 'Frutas', nombre: 'Sandía (1 tajada)', calorias: 45, proteinas: 0.5, carbohidratos: 11, porcion: '1 tajada' },
  { categoria: 'Frutas', nombre: 'Aguacate (1/2 unidad)', calorias: 120, proteinas: 1.5, carbohidratos: 6, porcion: 'medio aguacate' },
  { categoria: 'Frutas', nombre: 'Frutos secos (puñado)', calorias: 170, proteinas: 5, carbohidratos: 6, porcion: '30 g' },
  { categoria: 'Frutas', nombre: 'Kiwi (1 unidad)', calorias: 42, proteinas: 0.8, carbohidratos: 10, porcion: '1 kiwi' },
  { categoria: 'Frutas', nombre: 'Mango (1 unidad)', calorias: 100, proteinas: 1, carbohidratos: 25, porcion: '1 mango' },
  { categoria: 'Frutas', nombre: 'Piña (1 rodaja)', calorias: 40, proteinas: 0.4, carbohidratos: 11, porcion: '1 rodaja' },
  { categoria: 'Frutas', nombre: 'Melón (1 porción)', calorias: 50, proteinas: 0.5, carbohidratos: 12, porcion: '1 porción' },
  { categoria: 'Frutas', nombre: 'Cerezas (1 taza)', calorias: 90, proteinas: 1, carbohidratos: 22, porcion: '1 taza' },
  { categoria: 'Frutas', nombre: 'Arándanos (1 taza)', calorias: 85, proteinas: 1, carbohidratos: 21, porcion: '1 taza' },
  { categoria: 'Frutas', nombre: 'Frambuesas (1 taza)', calorias: 65, proteinas: 1.5, carbohidratos: 15, porcion: '1 taza' },
  { categoria: 'Frutas', nombre: 'Moras (1 taza)', calorias: 60, proteinas: 2, carbohidratos: 14, porcion: '1 taza' },
  { categoria: 'Frutas', nombre: 'Granada (1/2 unidad)', calorias: 55, proteinas: 1, carbohidratos: 13, porcion: 'media granada' },
  { categoria: 'Frutas', nombre: 'Papaya (1 taza)', calorias: 60, proteinas: 0.5, carbohidratos: 15, porcion: '1 taza' },
  { categoria: 'Frutas', nombre: 'Melocotón (1 unidad)', calorias: 60, proteinas: 1, carbohidratos: 14, porcion: '1 melocotón' },
  { categoria: 'Frutas', nombre: 'Albaricoque (1 unidad)', calorias: 17, proteinas: 0.5, carbohidratos: 4, porcion: '1 albaricoque' },
  { categoria: 'Frutas', nombre: 'Ciruela (1 unidad)', calorias: 30, proteinas: 0.5, carbohidratos: 8, porcion: '1 ciruela' },
  { categoria: 'Frutas', nombre: 'Higo (1 unidad)', calorias: 35, proteinas: 0.4, carbohidratos: 9, porcion: '1 higo' },
  { categoria: 'Frutas', nombre: 'Dátiles (3 unidades)', calorias: 70, proteinas: 0.5, carbohidratos: 18, porcion: '3 dátiles' },
  { categoria: 'Frutas', nombre: 'Maracuyá (1 unidad)', calorias: 17, proteinas: 0.4, carbohidratos: 4, porcion: '1 maracuyá' },
  { categoria: 'Frutas', nombre: 'Coco (1 trozo)', calorias: 140, proteinas: 1.5, carbohidratos: 6, porcion: '1 trozo 30 g' },
  { categoria: 'Frutas', nombre: 'Pomelo (1/2 unidad)', calorias: 40, proteinas: 0.8, carbohidratos: 10, porcion: 'medio pomelo' },
  { categoria: 'Frutas', nombre: 'Mandarina (1 unidad)', calorias: 45, proteinas: 0.6, carbohidratos: 11, porcion: '1 mandarina' },
  { categoria: 'Frutas', nombre: 'Lima (1 unidad)', calorias: 20, proteinas: 0.5, carbohidratos: 7, porcion: '1 lima' },
  { categoria: 'Frutas', nombre: 'Arándanos rojos (1 taza)', calorias: 50, proteinas: 0.5, carbohidratos: 13, porcion: '1 taza' },
  { categoria: 'Frutas', nombre: 'Higo chumbo / tuna (1 unidad)', calorias: 42, proteinas: 0.5, carbohidratos: 10, porcion: '1 unidad' },
  { categoria: 'Frutas', nombre: 'Guayaba (1 unidad)', calorias: 37, proteinas: 1.4, carbohidratos: 8, porcion: '1 guayaba' },
  { categoria: 'Frutas', nombre: 'Cantalupo (1 taza)', calorias: 50, proteinas: 0.5, carbohidratos: 12, porcion: '1 taza' },
  { categoria: 'Frutas', nombre: 'Sandía (1 taza en cubos)', calorias: 46, proteinas: 0.6, carbohidratos: 11, porcion: '1 taza' },
  { categoria: 'Frutas', nombre: 'Limón (1 unidad)', calorias: 17, proteinas: 0.6, carbohidratos: 5, porcion: '1 limón' },
  { categoria: 'Frutas', nombre: 'Nectarina (1 unidad)', calorias: 60, proteinas: 1, carbohidratos: 14, porcion: '1 nectarina' },
  { categoria: 'Frutas', nombre: 'Caqui / kaki (1 unidad)', calorias: 118, proteinas: 1, carbohidratos: 31, porcion: '1 unidad' },
  { categoria: 'Frutas', nombre: 'Uvas pasas (1 cucharada)', calorias: 85, proteinas: 0.5, carbohidratos: 22, porcion: '1 cucharada' },
  { categoria: 'Frutas', nombre: 'Higo seco (2 unidades)', calorias: 95, proteinas: 1, carbohidratos: 24, porcion: '2 higos' },
  { categoria: 'Frutas', nombre: 'Coco rallado (2 cucharadas)', calorias: 70, proteinas: 0.5, carbohidratos: 2.5, porcion: '2 cucharadas' },
  { categoria: 'Frutas', nombre: 'Fruta del dragón / pitaya (1 unidad)', calorias: 60, proteinas: 1, carbohidratos: 13, porcion: '1 unidad' },

  // Comidas compuestas
  { categoria: 'Platos típicos', nombre: 'Ensalada César con pollo', calorias: 450, proteinas: 35, carbohidratos: 25, porcion: '1 plato' },
  { categoria: 'Platos típicos', nombre: 'Pollo con arroz y verduras', calorias: 450, proteinas: 35, carbohidratos: 45, porcion: '1 plato' },
  { categoria: 'Platos típicos', nombre: 'Pasta con salsa de tomate', calorias: 380, proteinas: 12, carbohidratos: 65, porcion: '1 plato' },
  { categoria: 'Platos típicos', nombre: 'Pizza (2 porciones)', calorias: 500, proteinas: 22, carbohidratos: 60, porcion: '2 porciones' },
  { categoria: 'Platos típicos', nombre: 'Bocadillo de jamón y queso', calorias: 380, proteinas: 18, carbohidratos: 42, porcion: '1 unidad' },
  { categoria: 'Platos típicos', nombre: 'Sopa de verduras (1 bowl)', calorias: 80, proteinas: 3, carbohidratos: 15, porcion: '1 bowl' },
  { categoria: 'Platos típicos', nombre: 'Tortilla de patata (1 porción)', calorias: 280, proteinas: 12, carbohidratos: 22, porcion: '1 porción' },
  { categoria: 'Platos típicos', nombre: 'Bowl de quinoa con verduras', calorias: 350, proteinas: 12, carbohidratos: 50, porcion: '1 bowl' },
  { categoria: 'Platos típicos', nombre: 'Ensalada mixta con atún', calorias: 280, proteinas: 28, carbohidratos: 15, porcion: '1 plato' },
  { categoria: 'Platos típicos', nombre: 'Burrito (1 unidad)', calorias: 450, proteinas: 22, carbohidratos: 55, porcion: '1 burrito' },
  { categoria: 'Platos típicos', nombre: 'Tacos (3 unidades)', calorias: 330, proteinas: 18, carbohidratos: 42, porcion: '3 tacos' },
  { categoria: 'Platos típicos', nombre: 'Lasña (1 porción)', calorias: 400, proteinas: 22, carbohidratos: 38, porcion: '1 porción' },
  { categoria: 'Platos típicos', nombre: 'Risotto (1 plato)', calorias: 380, proteinas: 10, carbohidratos: 55, porcion: '1 plato' },
  { categoria: 'Platos típicos', nombre: 'Cazuela / guiso (1 plato)', calorias: 350, proteinas: 25, carbohidratos: 30, porcion: '1 plato' },
  { categoria: 'Platos típicos', nombre: 'Enchiladas (2 unidades)', calorias: 400, proteinas: 20, carbohidratos: 45, porcion: '2 enchiladas' },
  { categoria: 'Platos típicos', nombre: 'Ceviche (1 plato)', calorias: 180, proteinas: 28, carbohidratos: 12, porcion: '1 plato' },
  { categoria: 'Platos típicos', nombre: 'Milanesa con ensalada (1 porción)', calorias: 450, proteinas: 30, carbohidratos: 25, porcion: '1 porción' },
  { categoria: 'Platos típicos', nombre: 'Paella (1 plato)', calorias: 450, proteinas: 25, carbohidratos: 50, porcion: '1 plato' },
  { categoria: 'Platos típicos', nombre: 'Wrap / fajita (1 unidad)', calorias: 320, proteinas: 18, carbohidratos: 38, porcion: '1 wrap' },
  { categoria: 'Platos típicos', nombre: 'Sándwich club (1 unidad)', calorias: 550, proteinas: 28, carbohidratos: 45, porcion: '1 sándwich' },
  { categoria: 'Platos típicos', nombre: 'Sushi (6 piezas)', calorias: 250, proteinas: 10, carbohidratos: 38, porcion: '6 piezas' },
  { categoria: 'Platos típicos', nombre: 'Poke bowl (1 bowl)', calorias: 500, proteinas: 35, carbohidratos: 45, porcion: '1 bowl' },
  { categoria: 'Platos típicos', nombre: 'Omelette con verduras (2 huevos)', calorias: 220, proteinas: 16, carbohidratos: 8, porcion: '1 omelette' },

  // Comidas saludables — cereales integrales y pseudocereales
  { categoria: 'Comidas saludables', nombre: 'Avena en hojuelas (1 taza cocida)', calorias: 150, proteinas: 5, carbohidratos: 27, porcion: '1 taza' },
  { categoria: 'Comidas saludables', nombre: 'Quinoa cocida (1 taza)', calorias: 222, proteinas: 8, carbohidratos: 39, porcion: '1 taza' },
  { categoria: 'Comidas saludables', nombre: 'Bulgur cocido (1 taza)', calorias: 150, proteinas: 6, carbohidratos: 34, porcion: '1 taza' },
  { categoria: 'Comidas saludables', nombre: 'Cebada perlada cocida (1 taza)', calorias: 195, proteinas: 4, carbohidratos: 44, porcion: '1 taza' },
  { categoria: 'Comidas saludables', nombre: 'Amaranto cocido (1 taza)', calorias: 250, proteinas: 9, carbohidratos: 46, porcion: '1 taza' },
  { categoria: 'Comidas saludables', nombre: 'Mijo cocido (1 taza)', calorias: 205, proteinas: 6, carbohidratos: 41, porcion: '1 taza' },
  { categoria: 'Comidas saludables', nombre: 'Trigo sarraceno / alforfón (1 taza)', calorias: 155, proteinas: 6, carbohidratos: 34, porcion: '1 taza' },
  { categoria: 'Comidas saludables', nombre: 'Arroz salvaje (1 taza)', calorias: 165, proteinas: 7, carbohidratos: 35, porcion: '1 taza' },
  { categoria: 'Comidas saludables', nombre: 'Arroz integral basmati (1 taza)', calorias: 215, proteinas: 5, carbohidratos: 45, porcion: '1 taza' },
  { categoria: 'Comidas saludables', nombre: 'Trigo integral cocido (1 taza)', calorias: 230, proteinas: 9, carbohidratos: 48, porcion: '1 taza' },
  // Legumbres saludables
  { categoria: 'Comidas saludables', nombre: 'Lentejas rojas (1 taza)', calorias: 230, proteinas: 18, carbohidratos: 40, porcion: '1 taza' },
  { categoria: 'Comidas saludables', nombre: 'Porotos negros (1 taza)', calorias: 227, proteinas: 15, carbohidratos: 41, porcion: '1 taza' },
  { categoria: 'Comidas saludables', nombre: 'Porotos blancos / alubias (1 taza)', calorias: 225, proteinas: 15, carbohidratos: 40, porcion: '1 taza' },
  { categoria: 'Comidas saludables', nombre: 'Porotos mung (1 taza)', calorias: 212, proteinas: 14, carbohidratos: 39, porcion: '1 taza' },
  { categoria: 'Comidas saludables', nombre: 'Guisantes partidos (1 taza)', calorias: 230, proteinas: 16, carbohidratos: 41, porcion: '1 taza' },
  { categoria: 'Comidas saludables', nombre: 'Garbanzos (1 taza)', calorias: 270, proteinas: 15, carbohidratos: 45, porcion: '1 taza' },
  { categoria: 'Comidas saludables', nombre: 'Hummus casero (1/4 taza)', calorias: 105, proteinas: 4, carbohidratos: 12, porcion: '1/4 taza' },
  { categoria: 'Comidas saludables', nombre: 'Falafel (3 unidades)', calorias: 170, proteinas: 6, carbohidratos: 18, porcion: '3 unid' },
  // Semillas y frutos secos
  { categoria: 'Comidas saludables', nombre: 'Chía (2 cucharadas)', calorias: 120, proteinas: 4, carbohidratos: 10, porcion: '2 cucharadas' },
  { categoria: 'Comidas saludables', nombre: 'Linaza molida (2 cucharadas)', calorias: 75, proteinas: 3, carbohidratos: 4, porcion: '2 cucharadas' },
  { categoria: 'Comidas saludables', nombre: 'Semillas de girasol (30 g)', calorias: 175, proteinas: 6, carbohidratos: 7, porcion: '30 g' },
  { categoria: 'Comidas saludables', nombre: 'Semillas de calabaza (30 g)', calorias: 160, proteinas: 9, carbohidratos: 4, porcion: '30 g' },
  { categoria: 'Comidas saludables', nombre: 'Sésamo / ajonjolí (2 cucharadas)', calorias: 105, proteinas: 3, carbohidratos: 4, porcion: '2 cucharadas' },
  { categoria: 'Comidas saludables', nombre: 'Almendras (30 g)', calorias: 165, proteinas: 6, carbohidratos: 6, porcion: '30 g' },
  { categoria: 'Comidas saludables', nombre: 'Nueces (30 g)', calorias: 195, proteinas: 4.5, carbohidratos: 4, porcion: '30 g' },
  { categoria: 'Comidas saludables', nombre: 'Nueces de Brasil (4 unidades)', calorias: 130, proteinas: 3, carbohidratos: 3, porcion: '4 unid' },
  { categoria: 'Comidas saludables', nombre: 'Avellanas (30 g)', calorias: 180, proteinas: 4, carbohidratos: 5, porcion: '30 g' },
  { categoria: 'Comidas saludables', nombre: 'Pistachos (30 g)', calorias: 160, proteinas: 6, carbohidratos: 8, porcion: '30 g' },
  { categoria: 'Comidas saludables', nombre: 'Crema de almendras (1 cucharada)', calorias: 100, proteinas: 3, carbohidratos: 3, porcion: '1 cucharada' },
  { categoria: 'Comidas saludables', nombre: 'Mantequilla de maní natural (1 cucharada)', calorias: 95, proteinas: 4, carbohidratos: 3, porcion: '1 cucharada' },
  // Verduras y hortalizas saludables
  { categoria: 'Comidas saludables', nombre: 'Espinaca cruda (2 tazas)', calorias: 14, proteinas: 2, carbohidratos: 2, porcion: '2 tazas' },
  { categoria: 'Comidas saludables', nombre: 'Kale / col rizada (1 taza cruda)', calorias: 35, proteinas: 3, carbohidratos: 4, porcion: '1 taza' },
  { categoria: 'Comidas saludables', nombre: 'Brócoli al vapor (1 taza)', calorias: 55, proteinas: 4, carbohidratos: 11, porcion: '1 taza' },
  { categoria: 'Comidas saludables', nombre: 'Coliflor al vapor (1 taza)', calorias: 25, proteinas: 2, carbohidratos: 5, porcion: '1 taza' },
  { categoria: 'Comidas saludables', nombre: 'Zanahoria cruda (1 taza)', calorias: 52, proteinas: 1, carbohidratos: 12, porcion: '1 taza' },
  { categoria: 'Comidas saludables', nombre: 'Remolacha cocida (1 taza)', calorias: 75, proteinas: 3, carbohidratos: 17, porcion: '1 taza' },
  { categoria: 'Comidas saludables', nombre: 'Calabaza asada (1 taza)', calorias: 50, proteinas: 2, carbohidratos: 12, porcion: '1 taza' },
  { categoria: 'Comidas saludables', nombre: 'Espárragos (6 unidades)', calorias: 20, proteinas: 2, carbohidratos: 4, porcion: '6 unid' },
  { categoria: 'Comidas saludables', nombre: 'Pimiento rojo (1 unidad)', calorias: 45, proteinas: 2, carbohidratos: 9, porcion: '1 pimiento' },
  { categoria: 'Comidas saludables', nombre: 'Tomate cherry (1 taza)', calorias: 27, proteinas: 1, carbohidratos: 6, porcion: '1 taza' },
  { categoria: 'Comidas saludables', nombre: 'Aguacate (1/2 unidad)', calorias: 120, proteinas: 1.5, carbohidratos: 6, porcion: '1/2 unidad' },
  { categoria: 'Comidas saludables', nombre: 'Palta (1/2 unidad)', calorias: 120, proteinas: 1.5, carbohidratos: 6, porcion: '1/2 unidad' },
  { categoria: 'Comidas saludables', nombre: 'Alcachofa hervida (1 unidad)', calorias: 60, proteinas: 4, carbohidratos: 13, porcion: '1 unidad' },
  { categoria: 'Comidas saludables', nombre: 'Judías verdes al vapor (1 taza)', calorias: 35, proteinas: 2, carbohidratos: 8, porcion: '1 taza' },
  { categoria: 'Comidas saludables', nombre: 'Rúcula (2 tazas)', calorias: 10, proteinas: 1, carbohidratos: 1.5, porcion: '2 tazas' },
  { categoria: 'Comidas saludables', nombre: 'Canónigos (1 taza)', calorias: 10, proteinas: 1, carbohidratos: 2, porcion: '1 taza' },
  { categoria: 'Comidas saludables', nombre: 'Germinados de brócoli (1 taza)', calorias: 35, proteinas: 3, carbohidratos: 5, porcion: '1 taza' },
  { categoria: 'Comidas saludables', nombre: 'Berenjena al horno (1 taza)', calorias: 35, proteinas: 1, carbohidratos: 9, porcion: '1 taza' },
  { categoria: 'Comidas saludables', nombre: 'Calabacín a la plancha (1 taza)', calorias: 25, proteinas: 2, carbohidratos: 5, porcion: '1 taza' },
  // Frutas saludables
  { categoria: 'Comidas saludables', nombre: 'Manzana verde (1 unidad)', calorias: 95, proteinas: 0.5, carbohidratos: 25, porcion: '1 unidad' },
  { categoria: 'Comidas saludables', nombre: 'Pera (1 unidad)', calorias: 100, proteinas: 0.5, carbohidratos: 27, porcion: '1 unidad' },
  { categoria: 'Comidas saludables', nombre: 'Kiwi (1 unidad)', calorias: 42, proteinas: 0.8, carbohidratos: 10, porcion: '1 unidad' },
  { categoria: 'Comidas saludables', nombre: 'Arándanos (1 taza)', calorias: 85, proteinas: 1, carbohidratos: 21, porcion: '1 taza' },
  { categoria: 'Comidas saludables', nombre: 'Frambuesas (1 taza)', calorias: 65, proteinas: 1.5, carbohidratos: 15, porcion: '1 taza' },
  { categoria: 'Comidas saludables', nombre: 'Moras (1 taza)', calorias: 60, proteinas: 2, carbohidratos: 14, porcion: '1 taza' },
  { categoria: 'Comidas saludables', nombre: 'Fresas (1 taza)', calorias: 50, proteinas: 1, carbohidratos: 12, porcion: '1 taza' },
  { categoria: 'Comidas saludables', nombre: 'Granada (1/2 unidad)', calorias: 55, proteinas: 1, carbohidratos: 13, porcion: '1/2 unidad' },
  { categoria: 'Comidas saludables', nombre: 'Cerezas (1 taza)', calorias: 90, proteinas: 1, carbohidratos: 22, porcion: '1 taza' },
  { categoria: 'Comidas saludables', nombre: 'Ciruelas (2 unidades)', calorias: 60, proteinas: 1, carbohidratos: 16, porcion: '2 unid' },
  { categoria: 'Comidas saludables', nombre: 'Dátil natural (2 unidades)', calorias: 50, proteinas: 0.4, carbohidratos: 13, porcion: '2 unid' },
  { categoria: 'Comidas saludables', nombre: 'Higo fresco (2 unidades)', calorias: 70, proteinas: 0.8, carbohidratos: 18, porcion: '2 unid' },
  { categoria: 'Comidas saludables', nombre: 'Papaya (1 taza)', calorias: 60, proteinas: 0.5, carbohidratos: 15, porcion: '1 taza' },
  { categoria: 'Comidas saludables', nombre: 'Pomelo (1/2 unidad)', calorias: 40, proteinas: 0.8, carbohidratos: 10, porcion: '1/2 unidad' },
  { categoria: 'Comidas saludables', nombre: 'Naranja (1 unidad)', calorias: 62, proteinas: 1, carbohidratos: 15, porcion: '1 unidad' },
  { categoria: 'Comidas saludables', nombre: 'Mandarina (1 unidad)', calorias: 45, proteinas: 0.6, carbohidratos: 11, porcion: '1 unidad' },
  { categoria: 'Comidas saludables', nombre: 'Sandía (1 taza)', calorias: 46, proteinas: 0.6, carbohidratos: 11, porcion: '1 taza' },
  { categoria: 'Comidas saludables', nombre: 'Melón (1 taza)', calorias: 50, proteinas: 0.5, carbohidratos: 12, porcion: '1 taza' },
  { categoria: 'Comidas saludables', nombre: 'Mango (1 taza)', calorias: 100, proteinas: 1, carbohidratos: 25, porcion: '1 taza' },
  { categoria: 'Comidas saludables', nombre: 'Piña (1 taza)', calorias: 82, proteinas: 0.9, carbohidratos: 22, porcion: '1 taza' },
  { categoria: 'Comidas saludables', nombre: 'Banana / plátano (1 mediano)', calorias: 105, proteinas: 1, carbohidratos: 27, porcion: '1 unidad' },
  { categoria: 'Comidas saludables', nombre: 'Coco fresco (30 g)', calorias: 100, proteinas: 1, carbohidratos: 4, porcion: '30 g' },
  // Proteínas magras saludables
  { categoria: 'Comidas saludables', nombre: 'Pechuga de pollo a la plancha (150 g)', calorias: 165, proteinas: 31, carbohidratos: 0, porcion: '150 g' },
  { categoria: 'Comidas saludables', nombre: 'Pavo pechuga (150 g)', calorias: 165, proteinas: 30, carbohidratos: 0, porcion: '150 g' },
  { categoria: 'Comidas saludables', nombre: 'Salmón al horno (150 g)', calorias: 280, proteinas: 28, carbohidratos: 0, porcion: '150 g' },
  { categoria: 'Comidas saludables', nombre: 'Merluza / pescado blanco (150 g)', calorias: 120, proteinas: 26, carbohidratos: 0, porcion: '150 g' },
  { categoria: 'Comidas saludables', nombre: 'Atún al natural (1 lata)', calorias: 100, proteinas: 22, carbohidratos: 0, porcion: '1 lata' },
  { categoria: 'Comidas saludables', nombre: 'Huevo cocido (1 unidad)', calorias: 78, proteinas: 6, carbohidratos: 0.5, porcion: '1 huevo' },
  { categoria: 'Comidas saludables', nombre: 'Clara de huevo (2 unidades)', calorias: 34, proteinas: 7, carbohidratos: 0.5, porcion: '2 claras' },
  { categoria: 'Comidas saludables', nombre: 'Tofu firme (100 g)', calorias: 75, proteinas: 8, carbohidratos: 2, porcion: '100 g' },
  { categoria: 'Comidas saludables', nombre: 'Tempeh (100 g)', calorias: 195, proteinas: 20, carbohidratos: 9, porcion: '100 g' },
  { categoria: 'Comidas saludables', nombre: 'Edamame (1 taza)', calorias: 190, proteinas: 17, carbohidratos: 15, porcion: '1 taza' },
  { categoria: 'Comidas saludables', nombre: 'Seitan (100 g)', calorias: 120, proteinas: 24, carbohidratos: 4, porcion: '100 g' },
  { categoria: 'Comidas saludables', nombre: 'Carne magra de res (150 g)', calorias: 225, proteinas: 32, carbohidratos: 0, porcion: '150 g' },
  { categoria: 'Comidas saludables', nombre: 'Lomo de cerdo magro (150 g)', calorias: 250, proteinas: 28, carbohidratos: 0, porcion: '150 g' },
  { categoria: 'Comidas saludables', nombre: 'Camarones al vapor (100 g)', calorias: 100, proteinas: 24, carbohidratos: 0.5, porcion: '100 g' },
  // Lácteos y alternativas
  { categoria: 'Comidas saludables', nombre: 'Yogur griego natural 0% (1 unidad)', calorias: 100, proteinas: 17, carbohidratos: 6, porcion: '170 g' },
  { categoria: 'Comidas saludables', nombre: 'Yogur natural sin azúcar (1 unidad)', calorias: 70, proteinas: 5, carbohidratos: 8, porcion: '125 g' },
  { categoria: 'Comidas saludables', nombre: 'Leche desnatada (1 vaso)', calorias: 85, proteinas: 8, carbohidratos: 12, porcion: '250 ml' },
  { categoria: 'Comidas saludables', nombre: 'Leche de soja (1 vaso)', calorias: 80, proteinas: 7, carbohidratos: 4, porcion: '250 ml' },
  { categoria: 'Comidas saludables', nombre: 'Leche de almendras sin azúcar (1 vaso)', calorias: 40, proteinas: 1, carbohidratos: 2, porcion: '250 ml' },
  { categoria: 'Comidas saludables', nombre: 'Queso cottage bajo en grasa (1/2 taza)', calorias: 80, proteinas: 14, carbohidratos: 6, porcion: '1/2 taza' },
  { categoria: 'Comidas saludables', nombre: 'Requesón (1/2 taza)', calorias: 90, proteinas: 14, carbohidratos: 5, porcion: '1/2 taza' },
  { categoria: 'Comidas saludables', nombre: 'Queso fresco light (30 g)', calorias: 45, proteinas: 5, carbohidratos: 1, porcion: '30 g' },
  // Grasas saludables
  { categoria: 'Comidas saludables', nombre: 'Aceite de oliva virgen (1 cucharada)', calorias: 120, proteinas: 0, carbohidratos: 0, porcion: '1 cucharada' },
  { categoria: 'Comidas saludables', nombre: 'Aceite de coco (1 cucharada)', calorias: 120, proteinas: 0, carbohidratos: 0, porcion: '1 cucharada' },
  { categoria: 'Comidas saludables', nombre: 'Aguacate (1/4 unidad)', calorias: 60, proteinas: 0.8, carbohidratos: 3, porcion: '1/4 unidad' },
  // Bowls y platos saludables
  { categoria: 'Comidas saludables', nombre: 'Bowl de avena con fruta (1 bowl)', calorias: 350, proteinas: 12, carbohidratos: 58, porcion: '1 bowl' },
  { categoria: 'Comidas saludables', nombre: 'Bowl de quinoa con vegetales (1 bowl)', calorias: 380, proteinas: 14, carbohidratos: 52, porcion: '1 bowl' },
  { categoria: 'Comidas saludables', nombre: 'Buddha bowl con garbanzos (1 bowl)', calorias: 420, proteinas: 18, carbohidratos: 55, porcion: '1 bowl' },
  { categoria: 'Comidas saludables', nombre: 'Ensalada de garbanzos (1 plato)', calorias: 280, proteinas: 12, carbohidratos: 38, porcion: '1 plato' },
  { categoria: 'Comidas saludables', nombre: 'Ensalada verde con pollo (1 plato)', calorias: 320, proteinas: 35, carbohidratos: 12, porcion: '1 plato' },
  { categoria: 'Comidas saludables', nombre: 'Ensalada de lentejas (1 plato)', calorias: 300, proteinas: 18, carbohidratos: 42, porcion: '1 plato' },
  { categoria: 'Comidas saludables', nombre: 'Smoothie verde (1 vaso)', calorias: 120, proteinas: 4, carbohidratos: 22, porcion: '1 vaso' },
  { categoria: 'Comidas saludables', nombre: 'Smoothie de frutas y espinaca (1 vaso)', calorias: 150, proteinas: 3, carbohidratos: 32, porcion: '1 vaso' },
  { categoria: 'Comidas saludables', nombre: 'Porridge de avena (1 taza)', calorias: 200, proteinas: 7, carbohidratos: 35, porcion: '1 taza' },
  { categoria: 'Comidas saludables', nombre: 'Tostadas integrales con aguacate (2 unid)', calorias: 280, proteinas: 8, carbohidratos: 28, porcion: '2 tostadas' },
  { categoria: 'Comidas saludables', nombre: 'Huevos pochados con espinacas (2 huevos)', calorias: 200, proteinas: 14, carbohidratos: 4, porcion: '1 plato' },
  { categoria: 'Comidas saludables', nombre: 'Pescado al vapor con verduras (1 plato)', calorias: 280, proteinas: 32, carbohidratos: 18, porcion: '1 plato' },
  { categoria: 'Comidas saludables', nombre: 'Pollo con quinoa y ensalada (1 plato)', calorias: 420, proteinas: 42, carbohidratos: 38, porcion: '1 plato' },
  { categoria: 'Comidas saludables', nombre: 'Sopa de lentejas (1 bowl)', calorias: 220, proteinas: 14, carbohidratos: 35, porcion: '1 bowl' },
  { categoria: 'Comidas saludables', nombre: 'Sopa de verduras y garbanzos (1 bowl)', calorias: 180, proteinas: 8, carbohidratos: 28, porcion: '1 bowl' },
  { categoria: 'Comidas saludables', nombre: 'Crema de brócoli (1 bowl)', calorias: 120, proteinas: 6, carbohidratos: 18, porcion: '1 bowl' },
  { categoria: 'Comidas saludables', nombre: 'Tabulé (1 taza)', calorias: 140, proteinas: 4, carbohidratos: 26, porcion: '1 taza' },
  { categoria: 'Comidas saludables', nombre: 'Ensalada de quinoa (1 plato)', calorias: 280, proteinas: 10, carbohidratos: 38, porcion: '1 plato' },
  { categoria: 'Comidas saludables', nombre: 'Wrap integral con vegetales (1 unidad)', calorias: 280, proteinas: 12, carbohidratos: 42, porcion: '1 wrap' },
  { categoria: 'Comidas saludables', nombre: 'Tostada con hummus y tomate (2 unid)', calorias: 220, proteinas: 8, carbohidratos: 28, porcion: '2 tostadas' },
  { categoria: 'Comidas saludables', nombre: 'Boniato al horno (1 mediano)', calorias: 130, proteinas: 2, carbohidratos: 30, porcion: '1 unidad' },
  { categoria: 'Comidas saludables', nombre: 'Patata asada con piel (1 mediana)', calorias: 130, proteinas: 2, carbohidratos: 30, porcion: '1 unidad' },

  // Snacks y bebidas
  { categoria: 'Snacks / Bebidas', nombre: 'Barrita de cereales', calorias: 120, proteinas: 3, carbohidratos: 22, porcion: '1 unidad' },
  { categoria: 'Snacks / Bebidas', nombre: 'Frutos secos (puñado)', calorias: 170, proteinas: 5, carbohidratos: 6, porcion: '30 g' },
  { categoria: 'Snacks / Bebidas', nombre: 'Batido de proteínas', calorias: 120, proteinas: 25, carbohidratos: 3, porcion: '1 porción' },
  { categoria: 'Snacks / Bebidas', nombre: 'Zumo natural (1 vaso)', calorias: 110, proteinas: 1, carbohidratos: 26, porcion: '1 vaso' },
  { categoria: 'Snacks / Bebidas', nombre: 'Café solo', calorias: 2, proteinas: 0, carbohidratos: 0, porcion: '1 taza' },
  { categoria: 'Snacks / Bebidas', nombre: 'Té sin azúcar', calorias: 0, proteinas: 0, carbohidratos: 0, porcion: '1 taza' },
  { categoria: 'Snacks / Bebidas', nombre: 'Refresco con azúcar (1 vaso)', calorias: 100, proteinas: 0, carbohidratos: 26, porcion: '250 ml' },
  { categoria: 'Snacks / Bebidas', nombre: 'Agua', calorias: 0, proteinas: 0, carbohidratos: 0, porcion: '1 vaso' },
  { categoria: 'Snacks / Bebidas', nombre: 'Chocolate con leche (1 tableta)', calorias: 230, proteinas: 3, carbohidratos: 26, porcion: '40 g' },
  { categoria: 'Snacks / Bebidas', nombre: 'Galletas (3-4 unidades)', calorias: 150, proteinas: 2, carbohidratos: 22, porcion: '3-4 unid' },
  { categoria: 'Snacks / Bebidas', nombre: 'Palomitas naturales (1 taza)', calorias: 30, proteinas: 1, carbohidratos: 6, porcion: '1 taza' },
  { categoria: 'Snacks / Bebidas', nombre: 'Palomitas con mantequilla (1 taza)', calorias: 65, proteinas: 1, carbohidratos: 7, porcion: '1 taza' },
  { categoria: 'Snacks / Bebidas', nombre: 'Chips / patatas fritas bolsa', calorias: 150, proteinas: 2, carbohidratos: 15, porcion: '1 porción 30 g' },
  { categoria: 'Snacks / Bebidas', nombre: 'Gelatina (1 porción)', calorias: 80, proteinas: 2, carbohidratos: 18, porcion: '1 porción' },
  { categoria: 'Snacks / Bebidas', nombre: 'Helado (1 bola)', calorias: 140, proteinas: 2, carbohidratos: 20, porcion: '1 bola' },
  { categoria: 'Snacks / Bebidas', nombre: 'Té con leche', calorias: 30, proteinas: 2, carbohidratos: 3, porcion: '1 taza' },
  { categoria: 'Snacks / Bebidas', nombre: 'Café con leche y azúcar', calorias: 80, proteinas: 3, carbohidratos: 12, porcion: '1 taza' },
  { categoria: 'Snacks / Bebidas', nombre: 'Bebida isotónica (1 vaso)', calorias: 50, proteinas: 0, carbohidratos: 14, porcion: '250 ml' },
  { categoria: 'Snacks / Bebidas', nombre: 'Cerveza (1 vaso)', calorias: 150, proteinas: 1, carbohidratos: 13, porcion: '330 ml' },
  { categoria: 'Snacks / Bebidas', nombre: 'Vino tinto (1 copa)', calorias: 125, proteinas: 0, carbohidratos: 4, porcion: '1 copa' },
  { categoria: 'Snacks / Bebidas', nombre: 'Copa de vino blanco', calorias: 120, proteinas: 0, carbohidratos: 4, porcion: '1 copa' },
  { categoria: 'Snacks / Bebidas', nombre: 'Bizcocho (1 porción)', calorias: 250, proteinas: 4, carbohidratos: 35, porcion: '1 porción' },
  { categoria: 'Snacks / Bebidas', nombre: 'Magdalena (1 unidad)', calorias: 130, proteinas: 2, carbohidratos: 18, porcion: '1 magdalena' },
  { categoria: 'Snacks / Bebidas', nombre: 'Donut (1 unidad)', calorias: 250, proteinas: 4, carbohidratos: 30, porcion: '1 donut' },
  { categoria: 'Snacks / Bebidas', nombre: 'Almendras (puñado)', calorias: 165, proteinas: 6, carbohidratos: 6, porcion: '30 g' },
  { categoria: 'Snacks / Bebidas', nombre: 'Cacahuetes (puñado)', calorias: 170, proteinas: 7, carbohidratos: 6, porcion: '30 g' },
  { categoria: 'Snacks / Bebidas', nombre: 'Nueces (puñado)', calorias: 195, proteinas: 4.5, carbohidratos: 4, porcion: '30 g' },
  { categoria: 'Snacks / Bebidas', nombre: 'Limonada (1 vaso)', calorias: 90, proteinas: 0, carbohidratos: 25, porcion: '1 vaso' },
  { categoria: 'Snacks / Bebidas', nombre: 'Leche de almendras (1 vaso)', calorias: 40, proteinas: 1, carbohidratos: 2, porcion: '250 ml' },
  { categoria: 'Snacks / Bebidas', nombre: 'Leche de avena (1 vaso)', calorias: 120, proteinas: 3, carbohidratos: 16, porcion: '250 ml' },
  { categoria: 'Snacks / Bebidas', nombre: 'Chocolate negro (2 cuadrados)', calorias: 120, proteinas: 1.5, carbohidratos: 14, porcion: '20 g' },
  { categoria: 'Snacks / Bebidas', nombre: 'Tortilla de maíz (1 unidad)', calorias: 65, proteinas: 2, carbohidratos: 14, porcion: '1 tortilla' },
  { categoria: 'Snacks / Bebidas', nombre: 'Energía en barra', calorias: 110, proteinas: 2, carbohidratos: 22, porcion: '1 unidad' },
]

/** Agrupa por categoría para un selector */
export function getCategoriasUnicas() {
  const cats = [...new Set(REFERENCIA_ALIMENTOS.map((a) => a.categoria))]
  return cats
}

/** Buscar por nombre (texto). Devuelve items con _idx para aplicar. */
export function buscarAlimentos(texto) {
  if (!texto || texto.length < 1) return []
  const t = sinAcentos(texto.trim())
  return REFERENCIA_ALIMENTOS.map((a, idx) => ({ ...a, _idx: idx }))
    .filter(
      (a) =>
        sinAcentos(a.nombre).includes(t) ||
        sinAcentos(a.categoria).includes(t)
    )
    .slice(0, 100)
}
